In [2]:
%load_ext autoreload
%autoreload 2
import pandas as pd
from os.path import join as oj
import analyze_utils
import matplotlib.pyplot as plt
import iprompt
from tqdm import tqdm
from nltk.translate.bleu_score import sentence_bleu
import pickle as pkl
tqdm.pandas()
keys = ['model_cls', 'task_name', 'checkpoint', 'seed', 'gt_prompt']
keys_extra = ['n_shots', 'num_learned_tokens']
keys_out = ['reciprocal_rank', 'prefixes', 'iprompt_preprefix_str']

save_dir = '/home/chansingh/mntv1/iprompt_revision_xmas/'

In [3]:
# r = analyze_utils.load_results_and_cache_autoprompt_json(save_dir, save_file='r.pkl', one_row_only=True)
r = pd.read_pickle(oj(save_dir, 'r.pkl'))

In [4]:
# # subselect the data
r = r[r['n_shots'] == 5]
r = r[r['num_learned_tokens'] == 6]
# original suffix had a reranking step, correct one is just called "suff"
r = r[~(r['model_cls'] == 'suffix')]

# # add more keys
keys_derived = ['task_collection', 'top_prompt_correctness', 'bleu_top_prompt']
r['task_collection'] = r.task_name.apply(analyze_utils.task_collection)
r['top_prompt_correctness'] = r['reciprocal_rank'] == 1
r['gt_prompt'] = r['task_name'].apply(
    lambda x: iprompt.data.TASKS[x]['description'])
r['bleu_top_prompt'] = r.progress_apply(
    lambda x: sentence_bleu([x['gt_prompt'].split()],
                            x['prefixes'].split(), weights=(0.75, 0.25)), axis=1)  # maybe need to split before calling?

d = r[keys + keys_extra + keys_out + keys_derived]
d.to_pickle(oj(save_dir, 'd.pkl'))
d = pd.read_pickle(oj(save_dir, 'd.pkl'))

  0%|          | 0/2864 [00:00<?, ?it/s]/home/chansingh/.embgam/lib/python3.8/site-packages/nltk/translate/bleu_score.py:552: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
100%|██████████| 2864/2864 [00:00<00:00, 18634.18it/s]

# Metrics table

In [5]:
metrics = d.groupby(by=['model_cls', 'task_collection', 'checkpoint']).mean(numeric_only=True).reset_index()
ms = []
# with pd.option_context('display.float_format', lambda x: '%.1e' % x):
with pd.option_context('display.float_format', lambda x: '%.2g' % x):
    for ckpt in metrics.checkpoint.unique():
        m = (
            metrics[metrics.checkpoint == ckpt]
            .pivot_table(index='model_cls', columns='task_collection', values=['reciprocal_rank', 'top_prompt_correctness', 'bleu_top_prompt'])
            .transpose()
        )
        display(m)
        ms.append(m)

model_cls                               autoprompt  iprompt    suff
                       task_collection
bleu_top_prompt        ANLI                4.1e-80   0.0084 0.00071
                       DD                  1.1e-80   0.0018  0.0016
                       Induction             2e-79   0.0058 0.00096
                       Math                      0    6e-79  0.0078
reciprocal_rank        ANLI                  0.074     0.41    0.06
                       DD                   0.0036   0.0091   0.025
                       Induction             0.086     0.35   0.035
                       Math                   0.14     0.69   0.075
top_prompt_correctness ANLI                  0.074     0.37   0.011
                       DD                   0.0031        0   0.009
                       Induction              0.08     0.28  0.0089
                       Math                   0.13      0.6   0.034

model_cls                               autoprompt  iprompt    suff
                       task_collection
bleu_top_prompt        ANLI                3.8e-80     0.01 0.00032
                       DD                        0  2.9e-79  0.0015
                       Induction           2.7e-80    0.022  0.0027
                       Math                      0   0.0073 4.8e-79
reciprocal_rank        ANLI                 0.0025     0.39   0.085
                       DD                   0.0082    0.064   0.066
                       Induction             0.098     0.14   0.056
                       Math                   0.09      0.2   0.025
top_prompt_correctness ANLI                      0     0.34   0.025
                       DD                        0    0.043   0.052
                       Induction             0.087    0.071    0.02
                       Math                  0.075     0.12       0

model_cls                               autoprompt  iprompt    suff
                       task_collection
bleu_top_prompt        ANLI                    NaN   0.0029  0.0021
                       DD                        0    0.046 2.5e-79
                       Induction                 0    0.018 9.1e-05
                       Math                      0    0.025  0.0046
reciprocal_rank        ANLI                    NaN     0.26   0.057
                       DD                    0.014    0.089   0.005
                       Induction            0.0065     0.17   0.066
                       Math                  0.036     0.15   0.029
top_prompt_correctness ANLI                    NaN      0.2   0.024
                       DD                        0    0.074       0
                       Induction                 0     0.11   0.041
                       Math                      0      0.1   0.016

In [6]:
for m in ms:
    # put iprompt column first
    col = m['iprompt']
    m = m.drop(columns='iprompt')
    m.insert(loc=0, column='iprompt', value=col)

    # printing index
    mets_ordered = ['reciprocal_rank',
                    'top_prompt_correctness', 'bleu_top_prompt']
    collections_ordered = ['Math', 'ANLI', 'Induction']
    index = pd.MultiIndex.from_product([mets_ordered, collections_ordered])
    m[m < 1e-4] = 0
    m_s = (
        m
        .loc[index]  # reorder
        .applymap(lambda x: str.format("{:0.2g}", x))
        .apply(lambda x:
               [f"\\textbf{{{i}}}" if x.name ==
                'iprompt' else i for i in x],
               axis=0)
        .style.to_latex(hrules=True)
        .replace(' & task_collection &  &  &  \\\\\n', '')
        .replace(' & model_cls & iprompt & autoprompt & suff',  ' & & iPrompt & AutoPrompt & Suffix')
    )
    rename = {
        'reciprocal_rank': 'MRR',
        'top_prompt_correctness': 'Correctness',
        'bleu_top_prompt': 'BLEU',
    }
    for k in rename.keys():
        s = '\multirow[c]{3}{*}{' + k + '}'
        # print(s)
        m_s = m_s.replace(
            '\multirow[c]{3}{*}{' + k + '}',
            '\parbox[c]{0.3mm}{\multirow{3}{*}{\\rotatebox[origin = c]{90} {' + rename[k] + '}}}'
        )

    print(m_s)

\begin{tabular}{lllll}
\toprule
 & & iPrompt & AutoPrompt & Suffix \\
\midrule
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {MRR}}} & Math & \textbf{0.69} & 0.14 & 0.075 \\
 & ANLI & \textbf{0.41} & 0.074 & 0.06 \\
 & Induction & \textbf{0.35} & 0.086 & 0.035 \\
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {Correctness}}} & Math & \textbf{0.6} & 0.13 & 0.034 \\
 & ANLI & \textbf{0.37} & 0.074 & 0.011 \\
 & Induction & \textbf{0.28} & 0.08 & 0.0089 \\
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {BLEU}}} & Math & \textbf{0} & 0 & 0.0078 \\
 & ANLI & \textbf{0.0084} & 0 & 0.00071 \\
 & Induction & \textbf{0.0058} & 0 & 0.00096 \\
\bottomrule
\end{tabular}

\begin{tabular}{lllll}
\toprule
 & & iPrompt & AutoPrompt & Suffix \\
\midrule
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {MRR}}} & Math & \textbf{0.2} & 0.09 & 0.025 \\
 & ANLI & \textbf{0.39} & 0.0025 & 0.085 \\
 & Induction & \textbf{0.14} & 0.098 & 0.056 \\
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {Correctness}}} & Math & \textbf{0.12} & 0.075 & 0 \\
 & ANLI & \textbf{0.34} & 0 & 0.025 \\
 & Induction & \textbf{0.071} & 0.087 & 0.02 \\
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {BLEU}}} & Math & \textbf{0.0073} & 0 & 0 \\
 & ANLI & \textbf{0.01} & 0 & 0.00032 \\
 & Induction & \textbf{0.022} & 0 & 0.0027 \\
\bottomrule
\end{tabular}

\begin{tabular}{lllll}
\toprule
 & & iPrompt & AutoPrompt & Suffix \\
\midrule
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {MRR}}} & Math & \textbf{0.15} & 0.036 & 0.029 \\
 & ANLI & \textbf{0.26} & nan & 0.057 \\
 & Induction & \textbf{0.17} & 0.0065 & 0.066 \\
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {Correctness}}} & Math & \textbf{0.1} & 0 & 0.016 \\
 & ANLI & \textbf{0.2} & nan & 0.024 \\
 & Induction & \textbf{0.11} & 0 & 0.041 \\
\parbox[c]{0.3mm}{\multirow{3}{*}{\rotatebox[origin = c]{90} {BLEU}}} & Math & \textbf{0.025} & 0 & 0.0046 \\
 & ANLI & \textbf{0.0029} & nan & 0.0021 \\
 & Induction & \textbf{0.018} & 0 & 0 \\
\bottomrule
\end{tabular}

# Prompts table

In [44]:
for ckpt in d.checkpoint.unique():
    print(ckpt)
    prompts = d[d.checkpoint == ckpt]
    print(prompts.shape[0])
    prompts = (
        prompts
        .sort_values(by=['task_collection', 'reciprocal_rank'], ascending=False)
        .groupby(by=['model_cls', 'task_name'])
        .first()
    )
    # with pd.option_context('display.float_format', lambda x: '%.1e' % x):
    with pd.option_context('display.max_rows', None):
        tab = prompts[['prefixes']].pivot_table(index='task_name', columns='model_cls', values='prefixes', aggfunc=lambda x: ' '.join(x))
        # display(tab)
        with pd.option_context("max_colwidth", 1000):
            with open(f'{ckpt[:5]}.txt', 'w') as f:
                t = tab.fillna('').applymap(lambda x: '\\verb|' + x.replace('|', ' ')[:50] + '|')
                t.index = t.index.str.replace('_', ' ')
                s = t.to_latex(escape=False) #.replace('}', '\}').replace('{', '\{'
                s = ''.join([i if ord(i) < 128 else ' ' for i in s])
                s = s.replace('model_cls', '')
                s = s.replace('task_name', '')
                s = s.replace('\\begin{tabular}{llll}', '')
                f.write(s)

EleutherAI/gpt-j-6B
1327
google/flan-t5-xl
616
facebook/galactica-6.7b
921

/tmp/ipykernel_2450142/557738731.py:19: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  s = t.to_latex(escape=False) #.replace('}', '\}').replace('{', '\{'
/tmp/ipykernel_2450142/557738731.py:19: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  s = t.to_latex(escape=False) #.replace('}', '\}').replace('{', '\{'
/tmp/ipykernel_2450142/557738731.py:19: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  s = t.to_latex(escape=False) #.replace('}', '\}').replace('{', '\{'

# Prompts incomplete

In [8]:
for ckpt in d.checkpoint.unique():
    print(ckpt)
    prompts = d[d.checkpoint == ckpt]
    print(prompts.shape[0])
    prompts = (
        prompts
        .sort_values(by=['task_collection', 'reciprocal_rank'], ascending=False)
        .groupby(by=['model_cls', 'task_name'])
        .first()
    )
    # with pd.option_context('display.float_format', lambda x: '%.1e' % x):
    with pd.option_context('display.max_rows', None):
        tab = prompts[['prefixes']].pivot_table(index='task_name', columns='model_cls', values='prefixes', aggfunc=lambda x: ' '.join(x))
        display(tab[tab.isna().any(axis=1)])

EleutherAI/gpt-j-6B
1327

model_cls,autoprompt,iprompt,suff
task_name,,,
d3_0,NaN,line contains this string? No,"contains all 6 items, No"
task107_splash_question_to_sql,NaN,How Do You Connect SQL To,To get into MySQL you first

google/flan-t5-xl
616

model_cls,autoprompt,iprompt,suff
task_name,,,
active_to_passive,NaN,Answer: The judge encouraged the,Answer: The emperor
antonyms,NaN,What is the opposite of what,Answer: capitalism. Capitalis
common_concept,NaN,answer: sewing wrenches,For who are men? Answer
d3_0,Kö insects Et quarant Jacket würden,NaN,Answer: yes publique à
d3_1,NaN,NaN,no if it is
d3_10,NaN,Answer: no.||,Yes.; a).
d3_11,NaN,NaN,Answer: it is not possible
d3_12,NaN,NaN,yes|;e finally and
d3_13,NaN,NaN,Answer: yes What has caused
d3_14,NaN,Answer: yes or no?,Answer: yes?|E
d3_15,NaN,NaN,"no and yes, in"
d3_16,NaN,NaN,no please scroll down for the
d3_17,NaN,Answer: no - Twitter,Answer: yes if you
d3_18,NaN,NaN,"no ""they decide to tell"
d3_19,NaN,NaN,no i am a
d3_20,NaN,NaN,Answer: yes and no in
d3_21,NaN,NaN,Answer: yes in a
d3_22,NaN,NaN,Yes (necess
d3_24,NaN,NaN,no please scroll down for the
d3_25,NaN,NaN,No pts that
d3_26,NaN,NaN,yes if a woman
d3_27,NaN,is grammatical and,no please scroll down for the
d3_28,NaN,yes if the correct hashtag,no please block and/or
d3_29,NaN,NaN,"Answer: no ""Men"
d3_30,NaN,yes if a person,no|1|4|
d3_31,NaN,"yes while reading this article,",no for tyler
d3_33,NaN,NaN,no for the relevant sentence in
d3_35,NaN,NaN,Yesnodex is
d3_36,NaN,no when a noun,yes|<unk>?xm
d3_37,NaN,NaN,no when compared to the
d3_38,führtismul ravi Regi fictional pony,NaN,no while None of the below
d3_39,NaN,NaN,no to be clearer in
d3_4,NaN,NaN,no|No corresponding post
d3_40,NaN,NaN,yes in the first three queries
d3_41,NaN,NaN,Answer: yes and no in
d3_43,NaN,yes if the input tweet,Answer: yes and no at
d3_44,Antwortériimba keiner Kategorieschlaf,NaN,Answer: no Were the
d3_45,Zeitung territoirelicher ändern RFIDeste,NaN,no klso
d3_46,NaN,NaN,no <unk>nowiki>
d3_47,NaN,"yes. ""cancer""",No please. (A).
d3_48,NaN,Yes. This is a,no please scroll down for the
d3_49,NaN,"Is the word "" technology",No.|Po
d3_5,NaN,NaN,Answer: no print the answer
d3_50,NaN,NaN,"No, they would be forced"
d3_51,NaN,It is illegal to drop out,It's impossible to say
d3_52,NaN,"Yes, the topic is quantum",Answer: yes'.<unk>
d3_53,NaN,NaN,no is not an answer for
d3_6,NaN,NaN,Answer: some place different from
d3_7,NaN,Answer: no If the sentence,"Answer: no "" the third"
d3_8,NaN,NaN,Answer: yes and further stated
d3_9,NaN,NaN,"Answer: no ""Ma"
divide_two,NaN,Prompt: 9/,Answer: B. Given the
double_one,NaN,The factorial of the equation,What do some people in the
exp_one,NaN,What is the temperature of water,Which statement about the nature of
fibonacci_one,NaN,Pick your answer from the following,Question: What did the prophet
first_two,NaN,Choose the most meaningful number to,Answer: The first is that
informal_to_formal,NaN,Answer: Consider many approaches.,Answer: I am going to
larger_animal,NaN,Data. Which animal is larger,Name five reasons why you are
max_two,NaN,prompt: Which one is more,Answer: A. Pter
negation,NaN,Answer: Lebanon is not part,Answer: I did not do
orthography_starts_with,NaN,Choose from: a).,Answer: You would have to
rhymes,NaN,What do you call someone with,Test and explain why certain people
second_word_letter,NaN,Prompt: Select:,Answer: I grew in
sentence_similarity,NaN,Answer: 5 - likely,Answer: 1 - who
sentiment,NaN,"positivity or negativeness,",Answer: negative.It
square_one,NaN,What is the least common multiple,What does the f part
task088_identify_typo_verification,NaN,You need to list the letters,Answer: I don't
task092_check_prime_classification,NaN,No in the correct order:,Answer: [i] The
task107_splash_question_to_sql,NaN,What are several things you wish,Describe the nature of
task1146_country_capital,NaN,Answer: Minsk,For the name of a
task1147_country_currency,NaN,which currency is used in se,Which currency can I be sent
task1149_item_check_edible,NaN,Your code is incorrect. It,Answer: The name of the
task1191_food_veg_nonveg,NaN,does the following dish contain peanut,Answer: Yes. For the
task1336_peixian_equity_evaluation_corpus_gender_classifier,NaN,F or F? Which would,Answer: A. (e
task1509_evalution_antonyms,NaN,What word is the opposite of,How would you describe the sound
task183_rhyme_generation,NaN,what do you want in life,___ <unk>
taxonomy_animal,NaN,Answer: yellow.Input,Answer: a bee
translation_en-de,NaN,"Übersetzung into the Tat, die",int(input()
translation_en-es,NaN,span <unk> word in span,What was my son's
translation_en-fr,NaN,Prompt: Which one,Answer: Église
word_in_context,NaN,"Answer: same, not the",Answer: the same as in

facebook/galactica-6.7b
921

model_cls,autoprompt,iprompt,suff
task_name,,,
d3_2,propositional ScalarAsp Attacks train Rabin,NaN,contain any of given words otherwise
d3_44,wer: inducible affirm Abl reflex,NaN,contain any formals words or
task107_splash_question_to_sql,NaN,Question answering Input #Name,Is the following SQL clause equivalent

In [13]:
for ckpt in ['google/flan-t5-xl']:
    print(ckpt)
    prompts = d[d.checkpoint == ckpt]
    print(prompts.shape[0])
    prompts = (
        prompts
        .sort_values(by=['task_collection', 'reciprocal_rank'], ascending=False)
        .groupby(by=['model_cls', 'task_name'])
        .first()
    )
    # with pd.option_context('display.float_format', lambda x: '%.1e' % x):
    with pd.option_context('display.max_rows', None):
        tab = prompts[['prefixes']].pivot_table(index='task_name', columns='model_cls', values='prefixes', aggfunc=lambda x: ' '.join(x))
        display(tab[tab['iprompt'].isna()].index)

google/flan-t5-xl
616

Index(['d3_0', 'd3_1', 'd3_11', 'd3_12', 'd3_13', 'd3_15', 'd3_16', 'd3_18',
       'd3_19', 'd3_20', 'd3_21', 'd3_22', 'd3_24', 'd3_25', 'd3_26', 'd3_29',
       'd3_33', 'd3_35', 'd3_37', 'd3_38', 'd3_39', 'd3_4', 'd3_40', 'd3_41',
       'd3_44', 'd3_45', 'd3_46', 'd3_5', 'd3_50', 'd3_53', 'd3_6', 'd3_8',
       'd3_9'],
      dtype='object', name='task_name')