In [2]:
%load_ext autoreload
%autoreload 2
import pandas as pd
from os.path import join as oj
import analyze_utils
import matplotlib.pyplot as plt
import iprompt
from tqdm import tqdm
from nltk.translate.bleu_score import sentence_bleu
tqdm.pandas()

In [29]:
keys = ['model_cls', 'task_name', 'checkpoint', 'seed']
keys_extra = ['n_shots', 'num_learned_tokens']
keys_out = ['reciprocal_rank', 'prefixes', 'iprompt_preprefix_str']

save_dir = '/home/chansingh/mntv1/iprompt_revision_xmas/'

# r = analyze_utils.load_results_and_cache_autoprompt_json(save_dir, save_file='r.pkl')
r = pd.read_pickle(oj(save_dir, 'r.pkl'))

In [30]:
# # subselect the data
# r = r[r['n_shots'] == 5]
# r = r[r['num_learned_tokens'] == 6]

# # add more keys
# keys_derived = ['task_collection', 'top_prompt_correctness', 'bleu_top_prompt']
# r['task_collection'] = r.task_name.apply(analyze_utils.task_collection)
# r['top_prompt_correctness'] = r['reciprocal_rank'] == 1
# r['gt_prompt'] = r['task_name'].apply(lambda x: iprompt.data.TASKS[x]['description'])
# r['bleu_top_prompt'] = r.progress_apply(lambda x: sentence_bleu(x['gt_prompt'].split(), x['prefixes'].split()), axis=1) # maybe need to split before calling?

# d = r[keys + keys_extra + keys_out + keys_derived]
# d.to_pickle(oj(save_dir, 'd.pkl'))
d  = pd.read_pickle(oj(save_dir, 'd.pkl'))

(419705, 60)

In [31]:
d.shape

(419705, 12)

# Metrics table

In [10]:
metrics = d.groupby(by=['model_cls', 'task_collection', 'checkpoint']).mean(numeric_only=True).reset_index()
# with pd.option_context('display.float_format', lambda x: '%.1e' % x):
with pd.option_context('display.float_format', lambda x: '%.2g' % x):
    for ckpt in metrics.checkpoint.unique():
        print(ckpt)
        m = (
            metrics[metrics.checkpoint == ckpt]
            .pivot_table(index='model_cls', columns='task_collection', values=['reciprocal_rank', 'top_prompt_correctness', 'bleu_top_prompt'])
            .transpose()
        )
        display(m)

EleutherAI/gpt-j-6B

model_cls                               autoprompt  iprompt   suffix
                       task_collection
bleu_top_prompt        ANLI               5.8e-234 2.4e-232 1.1e-232
                       DD                 3.5e-235 8.1e-233 5.6e-233
                       Induction          2.8e-233 5.4e-159 7.5e-233
                       Math               2.8e-234 3.1e-232   3e-232
reciprocal_rank        ANLI                  0.054     0.43    1e-10
                       DD                  0.00034    0.009     0.05
                       Induction             0.099     0.35    0.071
                       Math                   0.12      0.7    0.052
top_prompt_correctness ANLI                  0.054     0.39        0
                       DD                        0        0    0.017
                       Induction             0.092     0.28    0.071
                       Math                   0.12     0.61    0.042

facebook/galactica-6.7b

model_cls                               autoprompt  iprompt   suffix
                       task_collection
bleu_top_prompt        ANLI               4.7e-234 1.8e-232 2.9e-232
                       DD                 4.5e-234 2.1e-232 1.6e-232
                       Induction          3.2e-233   7e-233 1.2e-232
                       Math                 8e-235 1.4e-232        0
reciprocal_rank        ANLI                 0.0051     0.58    1e-10
                       DD                    1e-10     0.26    0.026
                       Induction              0.12      0.2    1e-10
                       Math                   0.07     0.47     0.33
top_prompt_correctness ANLI                      0     0.52        0
                       DD                        0     0.16        0
                       Induction              0.11    0.062        0
                       Math                  0.042     0.39     0.33

google/flan-t5-xl

model_cls                               iprompt   suffix
                       task_collection
bleu_top_prompt        ANLI            1.5e-158 1.2e-232
                       DD              6.4e-233 5.9e-233
                       Induction        3.8e-81 1.2e-232
                       Math            3.2e-159 1.1e-232
reciprocal_rank        ANLI                0.27    1e-10
                       DD                 0.074    0.034
                       Induction           0.16    0.014
                       Math                0.16    1e-10
top_prompt_correctness ANLI                0.21        0
                       DD                 0.059    0.023
                       Induction          0.099        0
                       Math                 0.1        0

# Prompts table

In [34]:
for ckpt in d.checkpoint.unique():
    print(ckpt)
    prompts = d[d.checkpoint == ckpt]
    print(prompts.shape[0])
    prompts = (
        prompts
        .sort_values(by=['task_collection', 'reciprocal_rank'], ascending=False)
        .groupby(by=['model_cls', 'task_name'])
        .first()
    )
    # with pd.option_context('display.float_format', lambda x: '%.1e' % x):
    with pd.option_context('display.max_rows', None):
        display(prompts[['prefixes']].head())

EleutherAI/gpt-j-6B
246204

                                                                   prefixes
model_cls  task_name
autoprompt active_to_passive                            (= 18 the the subst
           add_two                 >:Returns Adding togetherFont accomplish
           antonyms                                      čthe bectheBut But
           cause_and_effect      REG Kinect virginity developed mosquit The
           common_concept     ???????? parted configuredthe        ????????

google/flan-t5-xl
134666

                                                     prefixes
model_cls task_name
iprompt   active_to_passive  Answer: The judge encouraged the
          add_two                     prompt: find the sum of
          antonyms               What is the opposite of what
          cause_and_effect                    Answer: Mary's.
          common_concept              answer: sewing wrenches

facebook/galactica-6.7b
38835

                                                              prefixes
model_cls  task_name
autoprompt add_two                                ě addthe Hyper� addi
           antonyms           meet equilibration stiptertead asymmetry
           cause_and_effect                      shaking Dthethethethe
           d3_26                                    NeuthePreftheDEthe
           d3_4                  MULT semilinear unarybuffer Gior fate

In [28]:
d.head(n=200)

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Which city is the capital and,NaN,ANLI,True,0.000000e+00
1,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Which city is the capital of,NaN,ANLI,True,0.000000e+00
2,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Which country is the capital of,NaN,ANLI,True,0.000000e+00
3,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Which country's capital is located,NaN,ANLI,True,0.000000e+00
4,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Which country's capital city is,NaN,ANLI,True,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...
195,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Enter a single city from your,NaN,ANLI,True,1.164047e-231
196,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Type out your name and the,NaN,ANLI,True,0.000000e+00
197,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Please choose the city of your,NaN,ANLI,True,0.000000e+00
198,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,Which city in the country is,NaN,ANLI,True,0.000000e+00
199,iprompt,task1146_country_capital,EleutherAI/gpt-j-6B,1,5,6,1.0,"""Who governs the United States",NaN,ANLI,True,0.000000e+00

In [19]:
for k, g in prompts:
    print(k)
    display(g.head())

('autoprompt', 'add_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,ě addthe Hyper� addi,,Math,True,0.0
1,autoprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,ě addthe Rep� addi,,Math,True,0.0
2,autoprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,ě adding restrrbracket$ addi,,Math,True,0.0
3,autoprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,ě adding rest countable� addi,,Math,True,0.0
4,autoprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,ě adding rest κ� addi,,Math,True,0.0

('autoprompt', 'antonyms')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.000000e-10,meet equilibration stiptertead asymmetry,,Induction,False,0.0
1,autoprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.000000e-10,meet reinforcement stip Paired continu asymmetry,,Induction,False,0.0
2,autoprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.000000e-10,meettert stipsubjectsead asymmetry,,Induction,False,0.0
3,autoprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.000000e-10,consequences Rayleigh conven Humans reversethe,,Induction,False,0.0
4,autoprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.000000e-10,ovesorem interpre Humansenerate asymmetry,,Induction,False,0.0

('autoprompt', 'cause_and_effect')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,cause_and_effect,facebook/galactica-6.7b,2,5,6,1.000000e-10,shaking Dthethethethe,,Induction,False,0.0
1,autoprompt,cause_and_effect,facebook/galactica-6.7b,2,5,6,1.000000e-10,doubled difthethepyrrol ws,,Induction,False,0.0
2,autoprompt,cause_and_effect,facebook/galactica-6.7b,2,5,6,1.000000e-10,WS difthethethe disp,,Induction,False,0.0
3,autoprompt,cause_and_effect,facebook/galactica-6.7b,2,5,6,1.000000e-10,doubled difthe receiver Sle cv,,Induction,False,0.0
4,autoprompt,cause_and_effect,facebook/galactica-6.7b,2,5,6,1.000000e-10,shaking Redthethethethe,,Induction,False,0.0

('autoprompt', 'd3_26')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,NeuthePreftheDEthe,Output yes if the input,DD,False,0.0
1,autoprompt,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,arski fused Constraints agendaBox dominated,Output yes if the input,DD,False,0.0
2,autoprompt,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,antitInd indirect lagged conflict dominated,Output yes if the input,DD,False,0.0
3,autoprompt,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,fl fused empty Celevik dominated,Output yes if the input,DD,False,0.0
4,autoprompt,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,arski fused Constraints asparBox dominated,Output yes if the input,DD,False,0.0

('autoprompt', 'd3_4')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,d3_4,facebook/galactica-6.7b,3,5,6,1.000000e-10,MULT semilinear unarybuffer Gior fate,Output yes if the input,DD,False,0.0
1,autoprompt,d3_4,facebook/galactica-6.7b,3,5,6,1.000000e-10,con downt Mall archae Closure calcd,Output yes if the input,DD,False,0.0
2,autoprompt,d3_4,facebook/galactica-6.7b,3,5,6,1.000000e-10,Kats atoms PIT JoshiONT stable,Output yes if the input,DD,False,0.0
3,autoprompt,d3_4,facebook/galactica-6.7b,3,5,6,1.000000e-10,operators Hofund pivotal Cir eosinophilic,Output yes if the input,DD,False,0.0
4,autoprompt,d3_4,facebook/galactica-6.7b,3,5,6,1.000000e-10,view Kui Philosophy ReasoningSM counterfactual,Output yes if the input,DD,False,0.0

('autoprompt', 'double_one')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,double_one,facebook/galactica-6.7b,1,5,6,0.013333,SumConstructtheulativeSeries Kip,,Math,False,0.0
1,autoprompt,double_one,facebook/galactica-6.7b,1,5,6,0.013333,Sum skiptheplicativeBatch superscript,,Math,False,0.0
2,autoprompt,double_one,facebook/galactica-6.7b,1,5,6,0.013333,SumConstructtheulativeSeries Kri,,Math,False,0.0
3,autoprompt,double_one,facebook/galactica-6.7b,1,5,6,0.013333,SumConstructtheulativeSeries sib,,Math,False,0.0
4,autoprompt,double_one,facebook/galactica-6.7b,1,5,6,0.013333,SumConstructtheulativeSeries Outer,,Math,False,0.0

('autoprompt', 'exp_one')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.029412,visc poplLSPLC Viscositythe,,Math,False,0.0
1,autoprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.029412,enthal Entry polysaccharide melts peric Param...,,Math,False,0.0
2,autoprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.029412,viscous Entry phPLC Viscositymeth,,Math,False,0.0
3,autoprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.029412,van Entry poly melts Viscositymeth,,Math,False,0.0
4,autoprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.029412,enthal Entry polystyrene ud ViscosityWOR,,Math,False,0.0

('autoprompt', 'first_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,first_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,AICthethethe Adethe,,Math,False,0.0
1,autoprompt,first_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,AICthethethe Houthe,,Math,False,0.0
2,autoprompt,first_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,AICthethethe adolesthe,,Math,False,0.0
3,autoprompt,first_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,AICthethethe Akaikethe,,Math,False,0.0
4,autoprompt,first_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,⇒alarial``---------------undraresis,,Math,False,0.0

('autoprompt', 'first_word_letter')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,first_word_letter,facebook/galactica-6.7b,1,5,6,1.000000e-10,d rthe l c syllable,,Induction,False,1.448850e-231
1,autoprompt,first_word_letter,facebook/galactica-6.7b,1,5,6,1.000000e-10,tathethethe wathe,,Induction,False,0.000000e+00
2,autoprompt,first_word_letter,facebook/galactica-6.7b,1,5,6,1.000000e-10,d rthe word c syllable,,Induction,False,1.218332e-231
3,autoprompt,first_word_letter,facebook/galactica-6.7b,1,5,6,1.000000e-10,d rthe a c syllable,,Induction,False,1.218332e-231
4,autoprompt,first_word_letter,facebook/galactica-6.7b,1,5,6,1.000000e-10,d rtheː jthe,,Induction,False,1.384293e-231

('autoprompt', 'larger_animal')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,larger_animal,facebook/galactica-6.7b,1,5,6,1.000000e-10,sharkoganopeanionaller descri,,Induction,False,0.0
1,autoprompt,larger_animal,facebook/galactica-6.7b,1,5,6,1.000000e-10,Tcthethethe ththe,,Induction,False,0.0
2,autoprompt,larger_animal,facebook/galactica-6.7b,1,5,6,1.000000e-10,Tcthethethe glthe,,Induction,False,0.0
3,autoprompt,larger_animal,facebook/galactica-6.7b,1,5,6,1.000000e-10,mix startheth ROTthe,,Induction,False,0.0
4,autoprompt,larger_animal,facebook/galactica-6.7b,1,5,6,1.000000e-10,mix starthethCPthe,,Induction,False,0.0

('autoprompt', 'max_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,max_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,$$amater Penet credible b,,Math,False,0.0
1,autoprompt,max_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,$$amater depolarizationcalc credible Turn,,Math,False,0.0
2,autoprompt,max_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,$$ depolarizationnonumber credible b,,Math,False,0.0
3,autoprompt,max_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,$$ evasionnonumber credible b,,Math,False,0.0
4,autoprompt,max_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,$$calcayasthe credible Activ,,Math,False,0.0

('autoprompt', 'multiply_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,multiply_two,facebook/galactica-6.7b,1,5,6,0.076923,aris visualthe Gibson multiplicative lexical,,Math,False,0.0
1,autoprompt,multiply_two,facebook/galactica-6.7b,1,5,6,0.076923,hens syllderr nonhuman multiplicative cognitive,,Math,False,0.0
2,autoprompt,multiply_two,facebook/galactica-6.7b,1,5,6,0.076923,ullnomthe nonhuman multiplicative mt,,Math,False,0.0
3,autoprompt,multiply_two,facebook/galactica-6.7b,1,5,6,0.076923,hens Gibsonderr nonhuman multiplicative cognitive,,Math,False,0.0
4,autoprompt,multiply_two,facebook/galactica-6.7b,1,5,6,0.076923,aris visualthe nonhuman multiplicative lexical,,Math,False,0.0

('autoprompt', 'num_to_verbal')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,num_to_verbal,facebook/galactica-6.7b,1,5,6,0.041667,anese Luoiral Orientedjing regul,,Induction,False,0.0
1,autoprompt,num_to_verbal,facebook/galactica-6.7b,1,5,6,0.041667,ɛ Polish allocation pronunciationourceMPL,,Induction,False,0.0
2,autoprompt,num_to_verbal,facebook/galactica-6.7b,1,5,6,0.041667,formewic Wales grammatical nilpotentDescriptor,,Induction,False,0.0
3,autoprompt,num_to_verbal,facebook/galactica-6.7b,1,5,6,0.041667,Card stream century Pip decimal County,,Induction,False,0.0
4,autoprompt,num_to_verbal,facebook/galactica-6.7b,1,5,6,0.041667,neurodegenerativeotinamide registered\t aria ...,,Induction,False,0.0

('autoprompt', 'orthography_starts_with')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,orthography_starts_with,facebook/galactica-6.7b,3,5,6,1.000000e-10,criptions geochemistry Harvey preprocessed Kus...,,Induction,False,0.0
1,autoprompt,orthography_starts_with,facebook/galactica-6.7b,3,5,6,1.000000e-10,Ntogh Perceptual tourist polic bowl,,Induction,False,0.0
2,autoprompt,orthography_starts_with,facebook/galactica-6.7b,3,5,6,1.000000e-10,sentenceerg� sparsopus mac,,Induction,False,0.0
3,autoprompt,orthography_starts_with,facebook/galactica-6.7b,3,5,6,1.000000e-10,lineage Tre Carpenter Shaw SIMD Bren,,Induction,False,0.0
4,autoprompt,orthography_starts_with,facebook/galactica-6.7b,3,5,6,1.000000e-10,tro lagged Has carers coffee Algorithms,,Induction,False,0.0

('autoprompt', 'rhymes')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,rhymes,facebook/galactica-6.7b,1,5,6,1.000000e-10,hallucinations song cooperationcorner ask smear,,Induction,False,0.0
1,autoprompt,rhymes,facebook/galactica-6.7b,1,5,6,1.000000e-10,meteor plvarkcorner orient shoe,,Induction,False,0.0
2,autoprompt,rhymes,facebook/galactica-6.7b,1,5,6,1.000000e-10,nee colothe penisrisonountain,,Induction,False,0.0
3,autoprompt,rhymes,facebook/galactica-6.7b,1,5,6,1.000000e-10,bloomohm cooperation dress marsh desensitization,,Induction,False,0.0
4,autoprompt,rhymes,facebook/galactica-6.7b,1,5,6,1.000000e-10,bloomohm cooperation dress Astrophysics desen...,,Induction,False,0.0

('autoprompt', 'singular_to_plural')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,singular_to_plural,facebook/galactica-6.7b,2,5,6,1.000000e-10,mes sequthethethethe,,Induction,False,0.0
1,autoprompt,singular_to_plural,facebook/galactica-6.7b,2,5,6,1.000000e-10,promisesext extr extr extremes auctions,,Induction,False,0.0
2,autoprompt,singular_to_plural,facebook/galactica-6.7b,2,5,6,1.000000e-10,volcanoesversus extrseg nons ips,,Induction,False,0.0
3,autoprompt,singular_to_plural,facebook/galactica-6.7b,2,5,6,1.000000e-10,promisesext extr extr extremes PDFs,,Induction,False,0.0
4,autoprompt,singular_to_plural,facebook/galactica-6.7b,2,5,6,1.000000e-10,remnants merid extr extrext ips,,Induction,False,0.0

('autoprompt', 'square_one')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,square_one,facebook/galactica-6.7b,1,5,6,1.000000e-10,AnalyticmassesAtomnamespace binning pow,,Math,False,0.0
1,autoprompt,square_one,facebook/galactica-6.7b,1,5,6,1.000000e-10,OPTmassesAtomnamespace multiplic Stellar,,Math,False,0.0
2,autoprompt,square_one,facebook/galactica-6.7b,1,5,6,1.000000e-10,AnalyticmassesAtomnamespace Continuum pow,,Math,False,0.0
3,autoprompt,square_one,facebook/galactica-6.7b,1,5,6,1.000000e-10,hurstullAtomnamespace multiplic Potentials,,Math,False,0.0
4,autoprompt,square_one,facebook/galactica-6.7b,1,5,6,1.000000e-10,keletonmassesAtomnamespace Physical pow,,Math,False,0.0

('autoprompt', 'subtract_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.2,ComplexRemthe scienti​Event,,Math,False,0.0
1,autoprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.2,Absolute cusp Symbolicarithm​,,Math,False,0.0
2,autoprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.2,Substit Answ Symbolicarithm​,,Math,False,0.0
3,autoprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.2,Absolute Gun Symbolicarithm​,,Math,False,0.0
4,autoprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.2,Complex subtractionthe scienti​Event,,Math,False,0.0

('autoprompt', 'sum')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,sum,facebook/galactica-6.7b,1,5,6,1.000000e-10,PageIndex​imgur mutually primes oste,,Induction,False,0.0
1,autoprompt,sum,facebook/galactica-6.7b,1,5,6,1.000000e-10,PageIndex​ Ultimate mutually primes oste,,Induction,False,0.0
2,autoprompt,sum,facebook/galactica-6.7b,1,5,6,1.000000e-10,PageIndex​ Brillouin mutually primes oste,,Induction,False,0.0
3,autoprompt,sum,facebook/galactica-6.7b,1,5,6,1.000000e-10,‐ BCAffe Montgomery primes quint,,Induction,False,0.0
4,autoprompt,sum,facebook/galactica-6.7b,1,5,6,1.000000e-10,LAB paralogcolour Montgomery primesarbon,,Induction,False,0.0

('autoprompt', 'task088_identify_typo_verification')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,0.083333,Etymology nom scalesrolateral QMples,,ANLI,False,0.0
1,autoprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,0.083333,suturethethe Th caud Thé,,ANLI,False,0.0
2,autoprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,0.083333,blunt anter antenn Thir Webboyal,,ANLI,False,0.0
3,autoprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,0.083333,Etymology som scalesonyms QMples,,ANLI,False,0.0
4,autoprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,0.083333,blunt anterobank Th Webboyal,,ANLI,False,0.0

('autoprompt', 'task092_check_prime_classification')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Accept No source ≤ Inter question,,ANLI,False,0.0
1,autoprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Accept No Ref ≤ Day Question,,ANLI,False,0.0
2,autoprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Accept No source ≤ Sum question,,ANLI,False,0.0
3,autoprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Accept No source ≤ Base question,,ANLI,False,0.0
4,autoprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Accept No Base ≤ Mode question,,ANLI,False,0.0

('autoprompt', 'task1146_country_capital')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,0.007812,Outer Hassan wal Tu Spontaneous Qu,,ANLI,False,0.0
1,autoprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,0.007812,Stam Claus squadhnurmonas,,ANLI,False,0.0
2,autoprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,0.007812,eri Serbian HO Ad midorum,,ANLI,False,0.0
3,autoprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,0.007812,geophysical Numer upl Johannesdic Kirch,,ANLI,False,0.0
4,autoprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,0.007812,osilicate meximi Dublin Shib cong,,ANLI,False,0.0

('autoprompt', 'task1147_country_currency')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.000000e-10,Llthethestr�the,,ANLI,False,0.0
1,autoprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.000000e-10,ena Neutral BenjaminiitenENE Neutral,,ANLI,False,0.0
2,autoprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.000000e-10,Sexthethethe Corthe,,ANLI,False,0.0
3,autoprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.000000e-10,LlthethetheVDthe,,ANLI,False,0.0
4,autoprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.000000e-10,Gren Neutral Neutralč Neut Treaty,,ANLI,False,0.0

('autoprompt', 'task1149_item_check_edible')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,1.000000e-10,nonthethe Characterizing Nothe,,ANLI,False,0.0
1,autoprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,1.000000e-10,yesno declare spacetime antim generic,,ANLI,False,0.0
2,autoprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,1.000000e-10,yesno constituent spacetime antimsoluble,,ANLI,False,0.0
3,autoprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,1.000000e-10,yes statements declare spacetime antimsoluble,,ANLI,False,0.0
4,autoprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,1.000000e-10,yesno phytochemicals spacetime antimsoluble,,ANLI,False,0.0

('autoprompt', 'task1191_food_veg_nonveg')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,1.000000e-10,gue axiomsepid Output yes Birk,,ANLI,False,0.0
1,autoprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,1.000000e-10,augmenting pygepid Output yes Birk,,ANLI,False,0.0
2,autoprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,1.000000e-10,Hell axiomsepid Output yes Birk,,ANLI,False,0.0
3,autoprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,1.000000e-10,augmenting Eriepid Output yes Birk,,ANLI,False,0.0
4,autoprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,1.000000e-10,forbidden Birkepid Output yes prone,,ANLI,False,0.0

('autoprompt', 'task1509_evalution_antonyms')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,Modern Carlson Weyl Linguistic counterfactual...,,ANLI,False,0.0
1,autoprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,Modern Carlson Weyl Linguistic coerconas,,ANLI,False,0.0
2,autoprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,gloss Carlson Weyl Linguistic counterfactual ...,,ANLI,False,0.0
3,autoprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,Stress Economy Weyl Linguistic counterfactual...,,ANLI,False,0.0
4,autoprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,garden crab Weyl Linguistic coerc Anderson,,ANLI,False,0.0

('autoprompt', 'task183_rhyme_generation')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,1.000000e-10,stellarthethethe pl battle,,ANLI,False,0.0
1,autoprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,1.000000e-10,stellarthethethe pocket pond,,ANLI,False,0.0
2,autoprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,1.000000e-10,stellarthe trenchthe pl pond,,ANLI,False,0.0
3,autoprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,1.000000e-10,stellarthethethe conduit pond,,ANLI,False,0.0
4,autoprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,1.000000e-10,liquidthetherae cr cr,,ANLI,False,0.0

('autoprompt', 'taxonomy_animal')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,taxonomy_animal,facebook/galactica-6.7b,2,5,6,1.000000e-10,duoull Pap codebook varic lysozyme,,Induction,False,0.0
1,autoprompt,taxonomy_animal,facebook/galactica-6.7b,2,5,6,1.000000e-10,Miaoull sick codebookonde po,,Induction,False,0.0
2,autoprompt,taxonomy_animal,facebook/galactica-6.7b,2,5,6,1.000000e-10,fibroblastull monot Chongickelotine,,Induction,False,0.0
3,autoprompt,taxonomy_animal,facebook/galactica-6.7b,2,5,6,1.000000e-10,fibroblastull worm codebook spinors quasars,,Induction,False,0.0
4,autoprompt,taxonomy_animal,facebook/galactica-6.7b,2,5,6,1.000000e-10,fibroblastull sick MMSEonde po,,Induction,False,0.0

('autoprompt', 'translation_en-de')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,translation_en-de,facebook/galactica-6.7b,1,5,6,1.000000e-10,shor Thanthe condens Intinte,,Induction,False,0.0
1,autoprompt,translation_en-de,facebook/galactica-6.7b,1,5,6,1.000000e-10,shor Thanthe conv Intinte,,Induction,False,0.0
2,autoprompt,translation_en-de,facebook/galactica-6.7b,1,5,6,1.000000e-10,shor Thanthe Dani Int Tz,,Induction,False,0.0
3,autoprompt,translation_en-de,facebook/galactica-6.7b,1,5,6,1.000000e-10,Tthethe int Intsl,,Induction,False,0.0
4,autoprompt,translation_en-de,facebook/galactica-6.7b,1,5,6,1.000000e-10,shor Thanthe Ron Int Tz,,Induction,False,0.0

('autoprompt', 'word_in_context')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,autoprompt,word_in_context,facebook/galactica-6.7b,1,5,6,1.0,""" Tang samethe offOff",,Induction,True,1.288230e-231
1,autoprompt,word_in_context,facebook/galactica-6.7b,1,5,6,1.0,agramsame samethe offOff,,Induction,True,0.000000e+00
2,autoprompt,word_in_context,facebook/galactica-6.7b,1,5,6,1.0,""" construction samethe offOff",,Induction,True,1.288230e-231
3,autoprompt,word_in_context,facebook/galactica-6.7b,1,5,6,1.0,noisesame samethe offOff,,Induction,True,0.000000e+00
4,autoprompt,word_in_context,facebook/galactica-6.7b,1,5,6,1.0,Discriminationsame samethe offOff,,Induction,True,0.000000e+00

('iprompt', 'active_to_passive')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,active_to_passive,facebook/galactica-6.7b,3,5,6,1.000000e-10,4-way Multiple Choice,,Induction,False,0.000000e+00
1,iprompt,active_to_passive,facebook/galactica-6.7b,3,5,6,1.000000e-10,(optional) Which of,,Induction,False,0.000000e+00
2,iprompt,active_to_passive,facebook/galactica-6.7b,3,5,6,1.000000e-10,Saved By a Tree?,,Induction,False,1.288230e-231
3,iprompt,active_to_passive,facebook/galactica-6.7b,3,5,6,1.000000e-10,Saved By a Lawyer,,Induction,False,1.288230e-231
4,iprompt,active_to_passive,facebook/galactica-6.7b,3,5,6,1.000000e-10,This time there are three entities,,Induction,False,0.000000e+00

('iprompt', 'add_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,In order to add two or,,Math,True,0.0
1,iprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,Given two decimal places show your,,Math,True,0.0
2,iprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,Let's see how this,,Math,True,0.0
3,iprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,Let's add some examples,,Math,True,0.0
4,iprompt,add_two,facebook/galactica-6.7b,1,5,6,1.0,When you add two whole number,,Math,True,0.0

('iprompt', 'antonyms')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.0,What is the opposite of each,,Induction,True,0.0
1,iprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.0,What is the opposite of what,,Induction,True,0.0
2,iprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.0,What is the opposite of?,,Induction,True,0.0
3,iprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.0,What is the opposite of a,,Induction,True,0.0
4,iprompt,antonyms,facebook/galactica-6.7b,3,5,6,1.0,“If the answer to your,,Induction,True,0.0

('iprompt', 'cause_and_effect')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,cause_and_effect,facebook/galactica-6.7b,1,5,6,0.021739,Find clues as to why each,,Induction,False,0.0
1,iprompt,cause_and_effect,facebook/galactica-6.7b,1,5,6,0.021739,"Given an ""entail",,Induction,False,0.0
2,iprompt,cause_and_effect,facebook/galactica-6.7b,1,5,6,0.021739,Explain what happened in each story,,Induction,False,0.0
3,iprompt,cause_and_effect,facebook/galactica-6.7b,1,5,6,0.021739,"{Premise,",,Induction,False,0.0
4,iprompt,cause_and_effect,facebook/galactica-6.7b,1,5,6,0.021739,How does your system perform on,,Induction,False,0.0

('iprompt', 'd3_28')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,d3_28,facebook/galactica-6.7b,3,5,6,0.5,has answer or nw otherwise,Output yes if the input,DD,False,0.0
1,iprompt,d3_28,facebook/galactica-6.7b,3,5,6,0.5,shows pro women or output maybe,Output yes if the input,DD,False,0.0
2,iprompt,d3_28,facebook/galactica-6.7b,3,5,6,0.5,is from women and don’,Output yes if the input,DD,False,0.0
3,iprompt,d3_28,facebook/galactica-6.7b,3,5,6,0.5,is from women and don',Output yes if the input,DD,False,0.0
4,iprompt,d3_28,facebook/galactica-6.7b,3,5,6,0.5,shows pro women or output No,Output yes if the input,DD,False,0.0

('iprompt', 'd3_31')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,d3_31,facebook/galactica-6.7b,2,5,6,1.000000e-10,"data contains a negative sentiment,",Output yes if the input,DD,False,1.218332e-231
1,iprompt,d3_31,facebook/galactica-6.7b,2,5,6,1.000000e-10,"question answers correctly. Otherwise,",Output yes if the input,DD,False,0.000000e+00
2,iprompt,d3_31,facebook/galactica-6.7b,2,5,6,1.000000e-10,describes a situation involving negative stere,Output yes if the input,DD,False,1.164047e-231
3,iprompt,d3_31,facebook/galactica-6.7b,2,5,6,1.000000e-10,sequence is a part-of,Output yes if the input,DD,False,1.288230e-231
4,iprompt,d3_31,facebook/galactica-6.7b,2,5,6,1.000000e-10,paragraph is a real news article,Output yes if the input,DD,False,1.164047e-231

('iprompt', 'd3_35')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,d3_35,facebook/galactica-6.7b,1,5,6,1.0,question contains YesNo words like,Output yes if the input,DD,True,0.0
1,iprompt,d3_35,facebook/galactica-6.7b,1,5,6,1.0,question contains YesNo words or,Output yes if the input,DD,True,0.0
2,iprompt,d3_35,facebook/galactica-6.7b,1,5,6,1.0,question contains YesNo words;,Output yes if the input,DD,True,0.0
3,iprompt,d3_35,facebook/galactica-6.7b,1,5,6,1.0,prompt matches our template for Yes,Output yes if the input,DD,True,0.0
4,iprompt,d3_35,facebook/galactica-6.7b,1,5,6,1.0,would seem like fake news,Output yes if the input,DD,True,0.0

('iprompt', 'd3_43')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,d3_43,facebook/galactica-6.7b,3,5,6,0.111111,supports my belief no otherwise Input,Output yes if the input,DD,False,0.000000e+00
1,iprompt,d3_43,facebook/galactica-6.7b,3,5,6,0.111111,sequence contains an answer Yes no,Output yes if the input,DD,False,0.000000e+00
2,iprompt,d3_43,facebook/galactica-6.7b,3,5,6,0.111111,satisfies ST and no otherwise e,Output yes if the input,DD,False,1.164047e-231
3,iprompt,d3_43,facebook/galactica-6.7b,3,5,6,0.111111,condition matches the truth of sem,Output yes if the input,DD,False,0.000000e+00
4,iprompt,d3_43,facebook/galactica-6.7b,3,5,6,0.111111,condition matches the truth table and,Output yes if the input,DD,False,0.000000e+00

('iprompt', 'd3_52')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,d3_52,facebook/galactica-6.7b,3,5,6,1.000000e-10,"phrase has the value no,",Output yes if the input,DD,False,0.0
1,iprompt,d3_52,facebook/galactica-6.7b,3,5,6,1.000000e-10,phrase has the value no es,Output yes if the input,DD,False,0.0
2,iprompt,d3_52,facebook/galactica-6.7b,3,5,6,1.000000e-10,no: The name of our,Output yes if the input,DD,False,0.0
3,iprompt,d3_52,facebook/galactica-6.7b,3,5,6,1.000000e-10,phrase has the value no and,Output yes if the input,DD,False,0.0
4,iprompt,d3_52,facebook/galactica-6.7b,3,5,6,1.000000e-10,phrase has the value no or,Output yes if the input,DD,False,0.0

('iprompt', 'd3_8')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,d3_8,facebook/galactica-6.7b,1,5,6,1.000000e-10,corresponds with prompt question ”no,Output yes if the input,DD,False,0.000000e+00
1,iprompt,d3_8,facebook/galactica-6.7b,1,5,6,1.000000e-10,"contained claims about ""no",Output yes if the input,DD,False,0.000000e+00
2,iprompt,d3_8,facebook/galactica-6.7b,1,5,6,1.000000e-10,was negative otherwise output else i,Output yes if the input,DD,False,1.164047e-231
3,iprompt,d3_8,facebook/galactica-6.7b,1,5,6,1.000000e-10,sentence contains ”no” and,Output yes if the input,DD,False,0.000000e+00
4,iprompt,d3_8,facebook/galactica-6.7b,1,5,6,1.000000e-10,sentence contains ”no” as,Output yes if the input,DD,False,0.000000e+00

('iprompt', 'diff')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,diff,facebook/galactica-6.7b,2,5,6,0.022727,Given two positive integers a and,,Induction,False,0.0
1,iprompt,diff,facebook/galactica-6.7b,2,5,6,0.022727,How many times is each digit,,Induction,False,0.0
2,iprompt,diff,facebook/galactica-6.7b,2,5,6,0.022727,Count the digits in each of,,Induction,False,0.0
3,iprompt,diff,facebook/galactica-6.7b,2,5,6,0.022727,Can you find all the digits,,Induction,False,0.0
4,iprompt,diff,facebook/galactica-6.7b,2,5,6,0.022727,How many times is the digit,,Induction,False,0.0

('iprompt', 'double_one')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,double_one,facebook/galactica-6.7b,1,5,6,0.125,We will now give you an,,Math,False,0.000000e+00
1,iprompt,double_one,facebook/galactica-6.7b,1,5,6,0.125,Is F continuous at all points,,Math,False,0.000000e+00
2,iprompt,double_one,facebook/galactica-6.7b,1,5,6,0.125,A car can be modeled as,,Math,False,0.000000e+00
3,iprompt,double_one,facebook/galactica-6.7b,1,5,6,0.125,Is F a linear function?,,Math,False,1.218332e-231
4,iprompt,double_one,facebook/galactica-6.7b,1,5,6,0.125,Is F a function? Explain,,Math,False,1.218332e-231

('iprompt', 'exp_one')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.023256,Given a number y and an,,Math,False,1.164047e-231
1,iprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.023256,Let g be defined by,,Math,False,1.218332e-231
2,iprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.023256,Suppose a man wants to buy,,Math,False,1.164047e-231
3,iprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.023256,Suppose that for all n in,,Math,False,1.164047e-231
4,iprompt,exp_one,facebook/galactica-6.7b,1,5,6,0.023256,For what values of a and,,Math,False,1.164047e-231

('iprompt', 'first_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,first_two,facebook/galactica-6.7b,1,5,6,0.004348,Solve using negative exponents? Explain,,Math,False,0.0
1,iprompt,first_two,facebook/galactica-6.7b,1,5,6,0.004348,Solve using negative exponents? If,,Math,False,0.0
2,iprompt,first_two,facebook/galactica-6.7b,1,5,6,0.004348,{Polar Equation of,,Math,False,0.0
3,iprompt,first_two,facebook/galactica-6.7b,1,5,6,0.004348,Solve using negative exponents? Given,,Math,False,0.0
4,iprompt,first_two,facebook/galactica-6.7b,1,5,6,0.004348,Solve using negative exponents? In,,Math,False,0.0

('iprompt', 'first_word_letter')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,first_word_letter,facebook/galactica-6.7b,2,5,6,0.5,What is the last word?,,Induction,False,0.0
1,iprompt,first_word_letter,facebook/galactica-6.7b,2,5,6,0.5,What is the first word of,,Induction,False,0.0
2,iprompt,first_word_letter,facebook/galactica-6.7b,2,5,6,0.5,What is the first letter of,,Induction,False,0.0
3,iprompt,first_word_letter,facebook/galactica-6.7b,2,5,6,0.5,What is the first word that,,Induction,False,0.0
4,iprompt,first_word_letter,facebook/galactica-6.7b,2,5,6,0.5,the word that _____,,Induction,False,0.0

('iprompt', 'max_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,max_two,facebook/galactica-6.7b,1,5,6,1.0,How large was each of your,,Math,True,0.000000e+00
1,iprompt,max_two,facebook/galactica-6.7b,1,5,6,1.0,Find five pairs of integers whose,,Math,True,0.000000e+00
2,iprompt,max_two,facebook/galactica-6.7b,1,5,6,1.0,Given an expression with one or,,Math,True,0.000000e+00
3,iprompt,max_two,facebook/galactica-6.7b,1,5,6,1.0,Given these fractions whose denominators,,Math,True,0.000000e+00
4,iprompt,max_two,facebook/galactica-6.7b,1,5,6,1.0,Simplify or find a mathematical,,Math,True,9.974863e-232

('iprompt', 'multiply_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,multiply_two,facebook/galactica-6.7b,1,5,6,1.0,When we multiply two even or,,Math,True,0.0
1,iprompt,multiply_two,facebook/galactica-6.7b,1,5,6,1.0,When we multiply two positive or,,Math,True,0.0
2,iprompt,multiply_two,facebook/galactica-6.7b,1,5,6,1.0,Given two integers a greater than,,Math,True,0.0
3,iprompt,multiply_two,facebook/galactica-6.7b,1,5,6,1.0,Given a set of two or,,Math,True,0.0
4,iprompt,multiply_two,facebook/galactica-6.7b,1,5,6,1.0,Given three consecutive even integers whose,,Math,True,0.0

('iprompt', 'negation')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,negation,facebook/galactica-6.7b,2,5,6,1.000000e-10,Find 5 pairs that you,,Induction,False,0.0
1,iprompt,negation,facebook/galactica-6.7b,2,5,6,1.000000e-10,The real number x has the,,Induction,False,0.0
2,iprompt,negation,facebook/galactica-6.7b,2,5,6,1.000000e-10,Find 5 other input-,,Induction,False,0.0
3,iprompt,negation,facebook/galactica-6.7b,2,5,6,1.000000e-10,A _____ represents the,,Induction,False,0.0
4,iprompt,negation,facebook/galactica-6.7b,2,5,6,1.000000e-10,When an algorithm or program can,,Induction,False,0.0

('iprompt', 'num_to_verbal')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,num_to_verbal,facebook/galactica-6.7b,2,5,6,0.047619,P(data|answer),,Induction,False,0.0
1,iprompt,num_to_verbal,facebook/galactica-6.7b,2,5,6,0.047619,Data for Common Sense Reasoning about,,Induction,False,0.0
2,iprompt,num_to_verbal,facebook/galactica-6.7b,2,5,6,0.047619,In an alphabet puzzle you are,,Induction,False,0.0
3,iprompt,num_to_verbal,facebook/galactica-6.7b,2,5,6,0.047619,Data for Common Sense Reasoning.,,Induction,False,0.0
4,iprompt,num_to_verbal,facebook/galactica-6.7b,2,5,6,0.047619,How many times are the digits,,Induction,False,0.0

('iprompt', 'second_word_letter')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,second_word_letter,facebook/galactica-6.7b,3,5,6,0.2,Please give the fifth vowel of,,Induction,False,0.0
1,iprompt,second_word_letter,facebook/galactica-6.7b,3,5,6,0.2,Please give the fifth vowel sound,,Induction,False,0.0
2,iprompt,second_word_letter,facebook/galactica-6.7b,3,5,6,0.2,Please give the fifth vowel letter,,Induction,False,0.0
3,iprompt,second_word_letter,facebook/galactica-6.7b,3,5,6,0.2,Please give the fifth vowel that,,Induction,False,0.0
4,iprompt,second_word_letter,facebook/galactica-6.7b,3,5,6,0.2,What is the second letter in,,Induction,False,0.0

('iprompt', 'singular_to_plural')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,singular_to_plural,facebook/galactica-6.7b,1,5,6,1.000000e-10,List the nouns formed from adding,,Induction,False,0.0
1,iprompt,singular_to_plural,facebook/galactica-6.7b,1,5,6,1.000000e-10,List the nouns formed by combining,,Induction,False,0.0
2,iprompt,singular_to_plural,facebook/galactica-6.7b,1,5,6,1.000000e-10,List the nouns formed from each,,Induction,False,0.0
3,iprompt,singular_to_plural,facebook/galactica-6.7b,1,5,6,1.000000e-10,List the nouns formed from these,,Induction,False,0.0
4,iprompt,singular_to_plural,facebook/galactica-6.7b,1,5,6,1.000000e-10,List the nouns in this sentence,,Induction,False,0.0

('iprompt', 'square_one')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,square_one,facebook/galactica-6.7b,1,5,6,0.004975,Given a number y and an,,Math,False,1.164047e-231
1,iprompt,square_one,facebook/galactica-6.7b,1,5,6,0.004975,Suppose we use a neural network,,Math,False,1.164047e-231
2,iprompt,square_one,facebook/galactica-6.7b,1,5,6,0.004975,How can you tell if a,,Math,False,1.164047e-231
3,iprompt,square_one,facebook/galactica-6.7b,1,5,6,0.004975,When did you learn about a,,Math,False,1.164047e-231
4,iprompt,square_one,facebook/galactica-6.7b,1,5,6,0.004975,True or False? Given a,,Math,False,1.218332e-231

('iprompt', 'subtract_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.066667,Given a variable called A whose,,Math,False,0.0
1,iprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.066667,Given a problem involving multiplication or,,Math,False,0.0
2,iprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.066667,Given two pairs of real or,,Math,False,0.0
3,iprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.066667,Find two integers whose sum or,,Math,False,0.0
4,iprompt,subtract_two,facebook/galactica-6.7b,1,5,6,0.066667,Find two integers whose product of,,Math,False,0.0

('iprompt', 'sum')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,sum,facebook/galactica-6.7b,1,5,6,0.034483,The number of days in a,,Induction,False,0.0
1,iprompt,sum,facebook/galactica-6.7b,1,5,6,0.034483,T/F Questions and Answ,,Induction,False,0.0
2,iprompt,sum,facebook/galactica-6.7b,1,5,6,0.034483,T/F Questions with Answ,,Induction,False,0.0
3,iprompt,sum,facebook/galactica-6.7b,1,5,6,0.034483,Write down three natural numbers whose,,Induction,False,0.0
4,iprompt,sum,facebook/galactica-6.7b,1,5,6,0.034483,Suppose the following questions are given,,Induction,False,0.0

('iprompt', 'task088_identify_typo_verification')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,1.000000e-10,(2-3),,ANLI,False,0.0
1,iprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Data for English-to-,,ANLI,False,0.0
2,iprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Something funny was going,,ANLI,False,0.0
3,iprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Who played football before Michael Jordan,,ANLI,False,0.0
4,iprompt,task088_identify_typo_verification,facebook/galactica-6.7b,1,5,6,1.000000e-10,Who was President Bill Clinton',,ANLI,False,0.0

('iprompt', 'task092_check_prime_classification')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,0.007194,Determine if every natural number has,,ANLI,False,0.0
1,iprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,0.007194,Determine if every natural number is,,ANLI,False,0.0
2,iprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,0.007194,The input question is “W,,ANLI,False,0.0
3,iprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,0.007194,The input question is “H,,ANLI,False,0.0
4,iprompt,task092_check_prime_classification,facebook/galactica-6.7b,1,5,6,0.007194,The input question is “Which,,ANLI,False,0.0

('iprompt', 'task1146_country_capital')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,1.0,List the capital cities in each,,ANLI,True,0.0
1,iprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,1.0,What is the capital of Nam,,ANLI,True,0.0
2,iprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,1.0,What is the capital city?,,ANLI,True,0.0
3,iprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,1.0,Find the capital cities in,,ANLI,True,0.0
4,iprompt,task1146_country_capital,facebook/galactica-6.7b,1,5,6,1.0,**What is the capital,,ANLI,True,0.0

('iprompt', 'task1147_country_currency')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.0,Find the most common currency in,,ANLI,True,0.0
1,iprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.0,A country’s currency is,,ANLI,True,0.0
2,iprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.0,A country's currency is,,ANLI,True,0.0
3,iprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.0,A country's currency may,,ANLI,True,0.0
4,iprompt,task1147_country_currency,facebook/galactica-6.7b,1,5,6,1.0,A country's currency can,,ANLI,True,0.0

('iprompt', 'task1149_item_check_edible')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,0.166667,Why is “no answer”,,ANLI,False,0.0
1,iprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,0.166667,Which product does not contain,,ANLI,False,0.0
2,iprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,0.166667,Why is “no” different,,ANLI,False,0.0
3,iprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,0.166667,Which is not a typical example,,ANLI,False,0.0
4,iprompt,task1149_item_check_edible,facebook/galactica-6.7b,1,5,6,0.166667,Which product does not exist,,ANLI,False,0.0

('iprompt', 'task1191_food_veg_nonveg')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,0.016393,Are you a native speaker of,,ANLI,False,1.164047e-231
1,iprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,0.016393,Have you ever been to the,,ANLI,False,0.000000e+00
2,iprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,0.016393,"Sayyes no, or yes",,ANLI,False,0.000000e+00
3,iprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,0.016393,Enter whether each sentence has a,,ANLI,False,1.164047e-231
4,iprompt,task1191_food_veg_nonveg,facebook/galactica-6.7b,1,5,6,0.016393,Enter whether each sentence has,,ANLI,False,0.000000e+00

('iprompt', 'task1509_evalution_antonyms')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.0,Find the opposite of each given,,ANLI,True,0.0
1,iprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.0,Find the opposite of ________,,ANLI,True,0.0
2,iprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.0,Find the opposite of a.,,ANLI,True,0.0
3,iprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.0,Find the opposite of each adj,,ANLI,True,0.0
4,iprompt,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.0,Find the opposite of each word,,ANLI,True,0.0

('iprompt', 'task183_rhyme_generation')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,0.5,The 6-letter word,,ANLI,False,0.0
1,iprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,0.5,Do the following words rhyme,,ANLI,False,0.0
2,iprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,0.5,Find the first letter of each,,ANLI,False,0.0
3,iprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,0.5,Puzzle the words in,,ANLI,False,0.0
4,iprompt,task183_rhyme_generation,facebook/galactica-6.7b,1,5,6,0.5,Puzzle the words.,,ANLI,False,0.0

('iprompt', 'translation_en-fr')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,translation_en-fr,facebook/galactica-6.7b,2,5,6,1.000000e-10,"En particulier, v",,Induction,False,0.000000e+00
1,iprompt,translation_en-fr,facebook/galactica-6.7b,2,5,6,1.000000e-10,enquête sur l,,Induction,False,1.384293e-231
2,iprompt,translation_en-fr,facebook/galactica-6.7b,2,5,6,1.000000e-10,le dossier (,,Induction,False,0.000000e+00
3,iprompt,translation_en-fr,facebook/galactica-6.7b,2,5,6,1.000000e-10,a/an _______,,Induction,False,0.000000e+00
4,iprompt,translation_en-fr,facebook/galactica-6.7b,2,5,6,1.000000e-10,When is a person born?,,Induction,False,1.218332e-231

('iprompt', 'word_in_context')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,iprompt,word_in_context,facebook/galactica-6.7b,3,5,6,0.166667,True Question Answering System Input Data,,Induction,False,0.000000e+00
1,iprompt,word_in_context,facebook/galactica-6.7b,3,5,6,0.166667,True Question Answering System Input Format,,Induction,False,0.000000e+00
2,iprompt,word_in_context,facebook/galactica-6.7b,3,5,6,0.166667,We consider how a sentence is,,Induction,False,1.164047e-231
3,iprompt,word_in_context,facebook/galactica-6.7b,3,5,6,0.166667,Are all words appearing in sentence,,Induction,False,0.000000e+00
4,iprompt,word_in_context,facebook/galactica-6.7b,3,5,6,0.166667,Complete sentence with missing word using,,Induction,False,0.000000e+00

('suffix', 'add_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,add_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,Evaluate all six of your answers,,Math,False,0.0
1,suffix,add_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,Is that as simple or complex,,Math,False,0.0
2,suffix,add_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,Evaluate all of your answers for,,Math,False,0.0
3,suffix,add_two,facebook/galactica-6.7b,1,5,6,1.000000e-10,Is that obvious? If not,,Math,False,0.0
0,suffix,add_two,facebook/galactica-6.7b,2,5,6,1.000000e-10,Fill in all of your home,,Math,False,0.0

('suffix', 'cause_and_effect')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,cause_and_effect,facebook/galactica-6.7b,1,5,6,1.000000e-10,Descriptions and Examples of Correct,,Induction,False,0.0
1,suffix,cause_and_effect,facebook/galactica-6.7b,1,5,6,1.000000e-10,Descriptions are needed for training,,Induction,False,0.0
2,suffix,cause_and_effect,facebook/galactica-6.7b,1,5,6,1.000000e-10,Question Generation Input Data for S,,Induction,False,0.0
3,suffix,cause_and_effect,facebook/galactica-6.7b,1,5,6,1.000000e-10,Question Generation Input \(,,Induction,False,0.0

('suffix', 'd3_1')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_1,facebook/galactica-6.7b,3,5,6,1.000000e-10,contains 5 words beginning with,Output yes if the input,DD,False,0.000000e+00
1,suffix,d3_1,facebook/galactica-6.7b,3,5,6,1.000000e-10,indicates that people get together but,Output yes if the input,DD,False,0.000000e+00
2,suffix,d3_1,facebook/galactica-6.7b,3,5,6,1.000000e-10,indicates that there is a marriage,Output yes if the input,DD,False,1.164047e-231
3,suffix,d3_1,facebook/galactica-6.7b,3,5,6,1.000000e-10,"contains ""married female",Output yes if the input,DD,False,0.000000e+00

('suffix', 'd3_13')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_13,facebook/galactica-6.7b,2,5,6,1.000000e-10,prompt contains an answer choice that,Output yes if the input,DD,False,0.0
1,suffix,d3_13,facebook/galactica-6.7b,2,5,6,1.000000e-10,contains this query and it is,Output yes if the input,DD,False,0.0
2,suffix,d3_13,facebook/galactica-6.7b,2,5,6,1.000000e-10,contains an answer with support provided,Output yes if the input,DD,False,0.0
3,suffix,d3_13,facebook/galactica-6.7b,2,5,6,1.000000e-10,prompt is given as question Input,Output yes if the input,DD,False,0.0

('suffix', 'd3_14')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_14,facebook/galactica-6.7b,3,5,6,1.000000e-10,has both negative polarity as well,Output yes if the input,DD,False,0.000000e+00
1,suffix,d3_14,facebook/galactica-6.7b,3,5,6,1.000000e-10,is one from D or E,Output yes if the input,DD,False,0.000000e+00
2,suffix,d3_14,facebook/galactica-6.7b,3,5,6,1.000000e-10,is tagged as either positive or,Output yes if the input,DD,False,0.000000e+00
3,suffix,d3_14,facebook/galactica-6.7b,3,5,6,1.000000e-10,has a positive effect on output,Output yes if the input,DD,False,8.340761e-232

('suffix', 'd3_15')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_15,facebook/galactica-6.7b,1,5,6,1.000000e-10,question contains Yes else output No,Output yes if the input,DD,False,0.0
1,suffix,d3_15,facebook/galactica-6.7b,1,5,6,1.000000e-10,contains words or phrases appearing between,Output yes if the input,DD,False,0.0
2,suffix,d3_15,facebook/galactica-6.7b,1,5,6,1.000000e-10,contains words or phrases containing information,Output yes if the input,DD,False,0.0
3,suffix,d3_15,facebook/galactica-6.7b,1,5,6,1.000000e-10,question contains Yes/No or,Output yes if the input,DD,False,0.0

('suffix', 'd3_2')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_2,facebook/galactica-6.7b,3,5,6,1.000000e-10,text fits into context or,Output yes if the input,DD,False,0.0
1,suffix,d3_2,facebook/galactica-6.7b,3,5,6,1.000000e-10,can be classified as both positive,Output yes if the input,DD,False,0.0
2,suffix,d3_2,facebook/galactica-6.7b,3,5,6,1.000000e-10,"text fits into (""",Output yes if the input,DD,False,0.0
3,suffix,d3_2,facebook/galactica-6.7b,3,5,6,1.000000e-10,can be classified as true answer,Output yes if the input,DD,False,0.0

('suffix', 'd3_23')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_23,facebook/galactica-6.7b,2,5,6,5.000000e-01,string is between A T E,Output yes if the input,DD,False,0.0
1,suffix,d3_23,facebook/galactica-6.7b,2,5,6,5.000000e-01,contains any word in the given,Output yes if the input,DD,False,0.0
2,suffix,d3_23,facebook/galactica-6.7b,2,5,6,5.000000e-01,is one sentence when in fact,Output yes if the input,DD,False,0.0
3,suffix,d3_23,facebook/galactica-6.7b,2,5,6,5.000000e-01,sequence is grammatical in English No,Output yes if the input,DD,False,0.0
0,suffix,d3_23,facebook/galactica-6.7b,3,5,6,1.000000e-10,indicates the presence of thor in,Output yes if the input,DD,False,0.0

('suffix', 'd3_24')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_24,facebook/galactica-6.7b,3,5,6,1.000000e-10,objective is satisfied else no f,Output yes if the input,DD,False,0.0
1,suffix,d3_24,facebook/galactica-6.7b,3,5,6,1.000000e-10,data are fit for iterative re,Output yes if the input,DD,False,0.0
2,suffix,d3_24,facebook/galactica-6.7b,3,5,6,1.000000e-10,objective is identified using the procedure,Output yes if the input,DD,False,0.0
3,suffix,d3_24,facebook/galactica-6.7b,3,5,6,1.000000e-10,data were identified according to assumptions,Output yes if the input,DD,False,0.0
0,suffix,d3_24,facebook/galactica-6.7b,1,5,6,1.000000e-10,is true or no otherwise;,Output yes if the input,DD,False,0.0

('suffix', 'd3_25')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_25,facebook/galactica-6.7b,3,5,6,1.000000e-10,belongs here according to what you,Output yes if the input,DD,False,0.0
1,suffix,d3_25,facebook/galactica-6.7b,3,5,6,1.000000e-10,is equal or less than five,Output yes if the input,DD,False,0.0
2,suffix,d3_25,facebook/galactica-6.7b,3,5,6,1.000000e-10,file consists at least one non,Output yes if the input,DD,False,0.0
3,suffix,d3_25,facebook/galactica-6.7b,3,5,6,1.000000e-10,is equal or larger than zero,Output yes if the input,DD,False,0.0

('suffix', 'd3_26')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,"matches what you were about,",Output yes if the input,DD,False,0.0
1,suffix,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,matches what you were about,Output yes if the input,DD,False,0.0
2,suffix,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,contains information that supports some concl...,Output yes if the input,DD,False,0.0
3,suffix,d3_26,facebook/galactica-6.7b,3,5,6,1.000000e-10,contains information that supports some claim,Output yes if the input,DD,False,0.0

('suffix', 'd3_27')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_27,facebook/galactica-6.7b,1,5,6,1.000000e-10,sentence is entailed by world,Output yes if the input,DD,False,0.000000e+00
1,suffix,d3_27,facebook/galactica-6.7b,1,5,6,1.000000e-10,"sentence has a match, and",Output yes if the input,DD,False,1.218332e-231
2,suffix,d3_27,facebook/galactica-6.7b,1,5,6,1.000000e-10,statement is one of your examples,Output yes if the input,DD,False,0.000000e+00
3,suffix,d3_27,facebook/galactica-6.7b,1,5,6,1.000000e-10,"statement corresponds, and output no",Output yes if the input,DD,False,0.000000e+00

('suffix', 'd3_28')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_28,facebook/galactica-6.7b,1,5,6,1.000000e-10,sentence contains Semitic languages and,Output yes if the input,DD,False,0.0
1,suffix,d3_28,facebook/galactica-6.7b,1,5,6,1.000000e-10,sentence contains both Semeval-,Output yes if the input,DD,False,0.0
2,suffix,d3_28,facebook/galactica-6.7b,1,5,6,1.000000e-10,sentence contains at least one positive,Output yes if the input,DD,False,0.0
3,suffix,d3_28,facebook/galactica-6.7b,1,5,6,1.000000e-10,sentence contains an active sexual har,Output yes if the input,DD,False,0.0

('suffix', 'd3_3')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_3,facebook/galactica-6.7b,2,5,6,0.25,says youtube or news,Output yes if the input,DD,False,0.0
1,suffix,d3_3,facebook/galactica-6.7b,2,5,6,0.25,says ‘Yes’; otherwise,Output yes if the input,DD,False,0.0
2,suffix,d3_3,facebook/galactica-6.7b,2,5,6,0.25,sentence matches with any one or,Output yes if the input,DD,False,0.0
3,suffix,d3_3,facebook/galactica-6.7b,2,5,6,0.25,sentence contains god or not?,Output yes if the input,DD,False,0.0

('suffix', 'd3_31')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_31,facebook/galactica-6.7b,3,5,6,1.000000e-10,is entailed by some knowledge,Output yes if the input,DD,False,0.000000e+00
1,suffix,d3_31,facebook/galactica-6.7b,3,5,6,1.000000e-10,bests a random baseline output,Output yes if the input,DD,False,1.218332e-231
2,suffix,d3_31,facebook/galactica-6.7b,3,5,6,1.000000e-10,"supports your choice, otherwise output",Output yes if the input,DD,False,0.000000e+00
3,suffix,d3_31,facebook/galactica-6.7b,3,5,6,1.000000e-10,"is from Group A, and",Output yes if the input,DD,False,0.000000e+00

('suffix', 'd3_32')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_32,facebook/galactica-6.7b,3,5,6,1.000000e-10,sentence contains “something interesting,Output yes if the input,DD,False,0.0
1,suffix,d3_32,facebook/galactica-6.7b,3,5,6,1.000000e-10,sentence contains such information or answer,Output yes if the input,DD,False,0.0
2,suffix,d3_32,facebook/galactica-6.7b,3,5,6,1.000000e-10,is Yes. Input No otherwise,Output yes if the input,DD,False,0.0
3,suffix,d3_32,facebook/galactica-6.7b,3,5,6,1.000000e-10,is affirmative. No otherwise,Output yes if the input,DD,False,0.0

('suffix', 'd3_33')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_33,facebook/galactica-6.7b,2,5,6,1.000000e-10,causes any of these programs in,Output yes if the input,DD,False,0.000000e+00
1,suffix,d3_33,facebook/galactica-6.7b,2,5,6,1.000000e-10,satisfies some logical theory about possible,Output yes if the input,DD,False,0.000000e+00
2,suffix,d3_33,facebook/galactica-6.7b,2,5,6,1.000000e-10,is legal and No otherwise.,Output yes if the input,DD,False,0.000000e+00
3,suffix,d3_33,facebook/galactica-6.7b,2,5,6,1.000000e-10,contains factual information and any,Output yes if the input,DD,False,0.000000e+00
0,suffix,d3_33,facebook/galactica-6.7b,1,5,6,1.000000e-10,text has a Yes/no,Output yes if the input,DD,False,1.288230e-231

('suffix', 'd3_37')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_37,facebook/galactica-6.7b,3,5,6,1.000000e-10,does not belong and output no,Output yes if the input,DD,False,0.000000e+00
1,suffix,d3_37,facebook/galactica-6.7b,3,5,6,1.000000e-10,does not belong and a random,Output yes if the input,DD,False,1.164047e-231
2,suffix,d3_37,facebook/galactica-6.7b,3,5,6,1.000000e-10,question can be answered correctly in,Output yes if the input,DD,False,0.000000e+00
3,suffix,d3_37,facebook/galactica-6.7b,3,5,6,1.000000e-10,question can be answered with an,Output yes if the input,DD,False,0.000000e+00

('suffix', 'd3_38')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_38,facebook/galactica-6.7b,3,5,6,1.000000e-10,refers outdated. Otherwise output,Output yes if the input,DD,False,0.0
1,suffix,d3_38,facebook/galactica-6.7b,3,5,6,1.000000e-10,belongs only to the YE,Output yes if the input,DD,False,0.0
2,suffix,d3_38,facebook/galactica-6.7b,3,5,6,1.000000e-10,belongs only to Yes and No,Output yes if the input,DD,False,0.0
3,suffix,d3_38,facebook/galactica-6.7b,3,5,6,1.000000e-10,refers outdated information. Input,Output yes if the input,DD,False,0.0

('suffix', 'd3_42')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_42,facebook/galactica-6.7b,2,5,6,1.000000e-10,data belongs to an organization and,Output yes if the input,DD,False,0.000000e+00
1,suffix,d3_42,facebook/galactica-6.7b,2,5,6,1.000000e-10,data belongs to an older population,Output yes if the input,DD,False,0.000000e+00
2,suffix,d3_42,facebook/galactica-6.7b,2,5,6,1.000000e-10,is not relevant to the discussion,Output yes if the input,DD,False,0.000000e+00
3,suffix,d3_42,facebook/galactica-6.7b,2,5,6,1.000000e-10,is not relevant or incomplete;,Output yes if the input,DD,False,0.000000e+00
0,suffix,d3_42,facebook/galactica-6.7b,1,5,6,1.000000e-10,is a real question and no,Output yes if the input,DD,False,9.853445e-232

('suffix', 'd3_46')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_46,facebook/galactica-6.7b,3,5,6,1.000000e-10,text contains any feeling about something,Output yes if the input,DD,False,0.0
1,suffix,d3_46,facebook/galactica-6.7b,3,5,6,1.000000e-10,text matches any of prompt,Output yes if the input,DD,False,0.0
2,suffix,d3_46,facebook/galactica-6.7b,3,5,6,1.000000e-10,sentence contains only one “do,Output yes if the input,DD,False,0.0
3,suffix,d3_46,facebook/galactica-6.7b,3,5,6,1.000000e-10,sentence contains at least one word,Output yes if the input,DD,False,0.0

('suffix', 'd3_51')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_51,facebook/galactica-6.7b,2,5,6,1.000000e-10,follows grammar rules Question no otherwise,Output yes if the input,DD,False,0.0
1,suffix,d3_51,facebook/galactica-6.7b,2,5,6,1.000000e-10,data requires more than some certain,Output yes if the input,DD,False,0.0
2,suffix,d3_51,facebook/galactica-6.7b,2,5,6,1.000000e-10,follows grammar rules or no otherwise,Output yes if the input,DD,False,0.0
3,suffix,d3_51,facebook/galactica-6.7b,2,5,6,1.000000e-10,data requires more than two tokens,Output yes if the input,DD,False,0.0

('suffix', 'd3_53')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_53,facebook/galactica-6.7b,2,5,6,1.000000e-10,"is a noun, and output",Output yes if the input,DD,False,8.166727e-232
1,suffix,d3_53,facebook/galactica-6.7b,2,5,6,1.000000e-10,is a picture and output no,Output yes if the input,DD,False,9.853445e-232
2,suffix,d3_53,facebook/galactica-6.7b,2,5,6,1.000000e-10,"is an HTML code, or",Output yes if the input,DD,False,0.000000e+00
3,suffix,d3_53,facebook/galactica-6.7b,2,5,6,1.000000e-10,"is correct, no otherwise.",Output yes if the input,DD,False,0.000000e+00
0,suffix,d3_53,facebook/galactica-6.7b,3,5,6,1.000000e-10,contains a sentence that starts with,Output yes if the input,DD,False,9.853445e-232

('suffix', 'd3_6')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_6,facebook/galactica-6.7b,1,5,6,1.000000e-10,contains any question mark followed by,Output yes if the input,DD,False,0.000000e+00
1,suffix,d3_6,facebook/galactica-6.7b,1,5,6,1.000000e-10,is confirmed as a positive sentence,Output yes if the input,DD,False,1.164047e-231
2,suffix,d3_6,facebook/galactica-6.7b,1,5,6,1.000000e-10,contains any keyword(2),Output yes if the input,DD,False,0.000000e+00
3,suffix,d3_6,facebook/galactica-6.7b,1,5,6,1.000000e-10,is confirmed; otherwise output no,Output yes if the input,DD,False,0.000000e+00

('suffix', 'd3_8')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_8,facebook/galactica-6.7b,3,5,6,1.000000e-10,matches with the correct definition as,Output yes if the input,DD,False,0.0
1,suffix,d3_8,facebook/galactica-6.7b,3,5,6,1.000000e-10,question contains key words? Q,Output yes if the input,DD,False,0.0
2,suffix,d3_8,facebook/galactica-6.7b,3,5,6,1.000000e-10,contains only words like this Question,Output yes if the input,DD,False,0.0
3,suffix,d3_8,facebook/galactica-6.7b,3,5,6,1.000000e-10,contains prompt for Yes/No,Output yes if the input,DD,False,0.0

('suffix', 'd3_9')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,d3_9,facebook/galactica-6.7b,3,5,6,1.000000e-10,contains a negative expression about some,Output yes if the input,DD,False,9.853445e-232
1,suffix,d3_9,facebook/galactica-6.7b,3,5,6,1.000000e-10,mention refers Yes Prompt:,Output yes if the input,DD,False,0.000000e+00
2,suffix,d3_9,facebook/galactica-6.7b,3,5,6,1.000000e-10,mention refers a new context or,Output yes if the input,DD,False,9.853445e-232
3,suffix,d3_9,facebook/galactica-6.7b,3,5,6,1.000000e-10,contains a correct answer; otherwise,Output yes if the input,DD,False,1.218332e-231

('suffix', 'divide_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,divide_two,facebook/galactica-6.7b,1,5,6,1.000000e+00,Divide two given fractions whose,,Math,True,0.0
1,suffix,divide_two,facebook/galactica-6.7b,1,5,6,1.000000e+00,Choose your answers as integers or,,Math,True,0.0
2,suffix,divide_two,facebook/galactica-6.7b,1,5,6,1.000000e+00,Choose your answers from a set,,Math,True,0.0
3,suffix,divide_two,facebook/galactica-6.7b,1,5,6,1.000000e+00,Divide two whole number answers,,Math,True,0.0
0,suffix,divide_two,facebook/galactica-6.7b,2,5,6,1.000000e-10,Find each ratio by using your,,Math,False,0.0

('suffix', 'first_word_letter')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,first_word_letter,facebook/galactica-6.7b,2,5,6,1.000000e-10,Describe the reason you would,,Induction,False,0.000000e+00
1,suffix,first_word_letter,facebook/galactica-6.7b,2,5,6,1.000000e-10,Describe the way in which,,Induction,False,0.000000e+00
2,suffix,first_word_letter,facebook/galactica-6.7b,2,5,6,1.000000e-10,[sigh] i,,Induction,False,1.531972e-231
3,suffix,first_word_letter,facebook/galactica-6.7b,2,5,6,1.000000e-10,"[sender],",,Induction,False,0.000000e+00

('suffix', 'informal_to_formal')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,informal_to_formal,facebook/galactica-6.7b,2,5,6,1.000000e-10,What are the correct questions?,,Induction,False,0.0
1,suffix,informal_to_formal,facebook/galactica-6.7b,2,5,6,1.000000e-10,What are the correct answers?,,Induction,False,0.0
2,suffix,informal_to_formal,facebook/galactica-6.7b,2,5,6,1.000000e-10,What does the answer mean?,,Induction,False,0.0
3,suffix,informal_to_formal,facebook/galactica-6.7b,2,5,6,1.000000e-10,What does the answer indicate?,,Induction,False,0.0

('suffix', 'multiply_two')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,multiply_two,facebook/galactica-6.7b,3,5,6,1.0,What happens when you multiply two,,Math,True,0.0
1,suffix,multiply_two,facebook/galactica-6.7b,3,5,6,1.0,What happens to this number after,,Math,True,0.0
2,suffix,multiply_two,facebook/galactica-6.7b,3,5,6,1.0,Which of these are true?,,Math,True,0.0
3,suffix,multiply_two,facebook/galactica-6.7b,3,5,6,1.0,Which of these relationships represents a,,Math,True,0.0

('suffix', 'sentence_similarity')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,sentence_similarity,facebook/galactica-6.7b,1,5,6,1.000000e-10,Please rate the naturalness of,,Induction,False,0.0
1,suffix,sentence_similarity,facebook/galactica-6.7b,1,5,6,1.000000e-10,Make your own claim about this,,Induction,False,0.0

('suffix', 'singular_to_plural')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,singular_to_plural,facebook/galactica-6.7b,3,5,6,1.000000e-10,I had some pretty bad dream,,Induction,False,0.0
1,suffix,singular_to_plural,facebook/galactica-6.7b,3,5,6,1.000000e-10,What would have made sense here,,Induction,False,0.0
2,suffix,singular_to_plural,facebook/galactica-6.7b,3,5,6,1.000000e-10,I had some pretty pictures of,,Induction,False,0.0
3,suffix,singular_to_plural,facebook/galactica-6.7b,3,5,6,1.000000e-10,What would have made the teacher,,Induction,False,0.0

('suffix', 'task092_check_prime_classification')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,task092_check_prime_classification,facebook/galactica-6.7b,3,5,6,1.000000e-10,What is the probability of a,,ANLI,False,1.164047e-231
1,suffix,task092_check_prime_classification,facebook/galactica-6.7b,3,5,6,1.000000e-10,What is the probability of rain,,ANLI,False,0.000000e+00
2,suffix,task092_check_prime_classification,facebook/galactica-6.7b,3,5,6,1.000000e-10,List of animals found in Pakistan,,ANLI,False,0.000000e+00
3,suffix,task092_check_prime_classification,facebook/galactica-6.7b,3,5,6,1.000000e-10,List of animals found on the,,ANLI,False,0.000000e+00

('suffix', 'task107_splash_question_to_sql')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,task107_splash_question_to_sql,facebook/galactica-6.7b,1,5,6,1.000000e-10,For some countries there is a,,ANLI,False,1.164047e-231
1,suffix,task107_splash_question_to_sql,facebook/galactica-6.7b,1,5,6,1.000000e-10,Select your personal favourite book,,ANLI,False,0.000000e+00
2,suffix,task107_splash_question_to_sql,facebook/galactica-6.7b,1,5,6,1.000000e-10,Select your personal favorite food from,,ANLI,False,0.000000e+00
3,suffix,task107_splash_question_to_sql,facebook/galactica-6.7b,1,5,6,1.000000e-10,For some countries you might be,,ANLI,False,0.000000e+00
0,suffix,task107_splash_question_to_sql,facebook/galactica-6.7b,2,5,6,1.000000e-10,"Question GenerationIn each iteration,",,ANLI,False,0.000000e+00

('suffix', 'task1146_country_capital')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,task1146_country_capital,facebook/galactica-6.7b,2,5,6,1.000000e-10,Can you provide an answer for,,ANLI,False,0.0
1,suffix,task1146_country_capital,facebook/galactica-6.7b,2,5,6,1.000000e-10,What's the most pop,,ANLI,False,0.0
2,suffix,task1146_country_capital,facebook/galactica-6.7b,2,5,6,1.000000e-10,Can you provide an example of,,ANLI,False,0.0
3,suffix,task1146_country_capital,facebook/galactica-6.7b,2,5,6,1.000000e-10,What's the name of,,ANLI,False,0.0

('suffix', 'task1509_evalution_antonyms')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,How can you tell from a,,ANLI,False,1.164047e-231
1,suffix,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,[(Skip),,ANLI,False,0.000000e+00
2,suffix,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,A word is missing! What,,ANLI,False,1.218332e-231
3,suffix,task1509_evalution_antonyms,facebook/galactica-6.7b,1,5,6,1.000000e-10,You are giving ten points to,,ANLI,False,0.000000e+00

('suffix', 'taxonomy_animal')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,taxonomy_animal,facebook/galactica-6.7b,3,5,6,1.000000e-10,[Image](..,,Induction,False,0.000000e+00
1,suffix,taxonomy_animal,facebook/galactica-6.7b,3,5,6,1.000000e-10,Weren't there more,,Induction,False,0.000000e+00
2,suffix,taxonomy_animal,facebook/galactica-6.7b,3,5,6,1.000000e-10,{} is a,,Induction,False,1.384293e-231
3,suffix,taxonomy_animal,facebook/galactica-6.7b,3,5,6,1.000000e-10,what color are you wearing?,,Induction,False,0.000000e+00
0,suffix,taxonomy_animal,facebook/galactica-6.7b,2,5,6,1.000000e-10,The following are examples of human,,Induction,False,0.000000e+00

('suffix', 'translation_en-es')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,translation_en-es,facebook/galactica-6.7b,3,5,6,1.000000e-10,Quizlet test with code,,Induction,False,0.000000e+00
1,suffix,translation_en-es,facebook/galactica-6.7b,3,5,6,1.000000e-10,Quiz 2 Input Questions,,Induction,False,0.000000e+00
2,suffix,translation_en-es,facebook/galactica-6.7b,3,5,6,1.000000e-10,A man is trying to sell,,Induction,False,0.000000e+00
3,suffix,translation_en-es,facebook/galactica-6.7b,3,5,6,1.000000e-10,A man asks a robot to,,Induction,False,9.853445e-232
0,suffix,translation_en-es,facebook/galactica-6.7b,1,5,6,1.000000e-10,(answer option is presented,,Induction,False,0.000000e+00

('suffix', 'word_in_context')

,model_cls,task_name,checkpoint,seed,n_shots,num_learned_tokens,reciprocal_rank,prefixes,iprompt_preprefix_str,task_collection,top_prompt_correctness,bleu_top_prompt
0,suffix,word_in_context,facebook/galactica-6.7b,1,5,6,1.000000e-10,"Given two sentences, decide if",,Induction,False,0.0
1,suffix,word_in_context,facebook/galactica-6.7b,1,5,6,1.000000e-10,"Given two sentences, identify similar",,Induction,False,0.0
2,suffix,word_in_context,facebook/galactica-6.7b,1,5,6,1.000000e-10,Given an input sentence pair and,,Induction,False,0.0
3,suffix,word_in_context,facebook/galactica-6.7b,1,5,6,1.000000e-10,"Given an input sentence pair,",,Induction,False,0.0

In [13]:
d.columns

Index(['model_cls', 'task_name', 'checkpoint', 'seed', 'n_shots',
       'num_learned_tokens', 'reciprocal_rank', 'prefixes',
       'iprompt_preprefix_str', 'task_collection', 'top_prompt_correctness',
       'bleu_top_prompt'],
      dtype='object')

In [ ]:
group_keys = ['model_cls', 'task_name', 'num_learned_tokens', 'n_shots', 'checkpoint', 'seed']
# metric = 'prefix_test_acc'
df = d[d['model_cls'] == 'iprompt']
with pd.option_context('display.max_rows', None):
    # display(r.groupby(group_keys)['prefixes'].max())
    display(df.groupby(group_keys).first()[['prefixes']].sort_values(by=['model_cls', 'task_name']).iloc[::-1])

In [33]:
df.groupby(group_keys).size()

model_cls  task_name          num_learned_tokens  n_shots  checkpoint               seed
iprompt    active_to_passive  6                   5        EleutherAI/gpt-j-6B      1        313
                                                                                    2        538
                                                                                    3        616
                                                           facebook/galactica-6.7b  3        543
                                                           google/flan-t5-xl        1       1024
                                                                                            ...
           word_in_context    6                   5        EleutherAI/gpt-j-6B      2        506
                                                                                    3        520
                                                           facebook/galactica-6.7b  3        290
                                                           google/flan-t5-xl        1       1024
                                                                                    2       1024
Length: 464, dtype: int64